version: '3'

services:

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-local/mysql/my.cnf:/etc/my.cnf
      - ./db/schema.sql:/docker-local-entrypoint-initdb.d/schema.sql
    restart: always

  drupal:
    depends_on:
      - db
    build: ./docker-local
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    restart: always

# Persistent sql storage
volumes:
  db_data:
